language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
